### PR TITLE
Make Quick Start more approachable

### PR DESCRIPTION
**Pull request by livike**
At DragonSprint we sent people over the Flask front page. Then we sent them over
the TryPyramid front page. Both “above the fold“. The difference was staggering:
all managed to start the Flask example and got a browser to render “Hello
World“. And none managed to do it with Pyramid without help or frustration.

This is our attempt to make TryPyramid QuickStart example more approachable.

Change 1: the Quick Start code configures the view imperatively and the Pyramid
Feature sections provide declarative examples. Lets promote a single way of view configuration, at least for newcomers.

Change 2: Every single person who tried the Quick Start code today got stuck
with a 404 Not Found error when running the code and opening it in the browser.
Because one needs to go to ``/hello/foo`` to get a response. This is not obvious
at all and people get stuck. Also, while it is nice to show off some Pyramid
features, let’s keep this example as simple as possible and return a hardcoded
string, on root. Several less things to get stuck on.

screenshot 2016-12-05 14 51 19

### CODE REVIEW

**Comment by stevepiercy** [comment]
I see three issues.

(1) The code on trypyramid.com must be consistent with the code in the official docs and its supported branches.

* http://docs.pylonsproject.org/projects/pyramid/en/master/
* http://docs.pylonsproject.org/projects/pyramid/en/latest/
* http://docs.pylonsproject.org/projects/pyramid/en/1.6-branch/

(2) I agree the code could be simplified to serve a plain old text response without a dynamic "foo" argument, but it also make it less interesting. Instead I'd prefer adding just the comment of where to point the browser with the argument and existing code, i.e., `http://localhost:8080/hello/foo`

(3) Telling users to install packages into their system Python via `pip install pyramid` is a bad thing™. That's why we have a link to detailed installation instructions, to account for different Python versions, virtual environments, and package management tools.

**Comment by zupo** [comment]
(1) Meaning we should change this code or meaning we should update docs when this is merged?

(2) We tried, people still get stuck. I know it's less interesting, but this code is not really meant to be interesting. It's meant to show how small a file you can run Pyramid off of.

(3) Firstly: everyone here implicitly typed ``virtualenv ...`` before trying the code. I guess the Python community's effort to tell everyone to use isolated environments worked well. That said, I'm semi OK with prepending ``virtualenv hello && cd hello && source bin/activate``. It will make the the second part of the example 100% longer.

**Comment by blaflamme** [comment]
I do think it's a good point to have a simple app exposed on the front page to give people a feel of what pyramid is. OTOH I don't think it's the right place to explain how to have a working environment and best practices. I think we should then provide a link to the right resource where it's better explained to be sure people don,t screw up things and keep the front page as minimal as possible in that regard.

A lot of other frameworks just expose snippets for that purpose, nothing runnable and it performs well.

**Comment by zupo** [comment]
FYI: we changed the response from ``{'content': 'Hello World'}`` to just ``Hello World`` as per discussion on IRC.

**Comment by zupo** [comment]
> A lot of other frameworks just expose snippets for that purpose, nothing runnable and it performs well.

Can you please point to those that you consider good examples? So we can take a look at them and see if we can learn from them.

**Comment by stevepiercy** [comment]
(1) Either way. If one is changed, then all others should be changed for consistency.

(2) OK. I concede a simple "Visit `http://localhost:8080/`" and code to match is more desirable.

(3) We have one and only one set of [installation instructions](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/install.html). Python 3.4+ now uses `python -m venv env`. Additionally we do not advocate the use of `activate`, and advise against its use, especially for newbies.

We have cookiecutters, too, so installation instructions might change again. And who knows what the PyPA will come up with next?

Finally, this is a marketing website and a launch pad to tutorials and other resources, not a tutorial or how-to itself.

**Comment by blaflamme** [comment]
@zupo 

https://laravel.com
https://www.playframework.com

**Comment by zupo** [comment]
OK, let's take it step by step. IIUC, the minimal changes that most of us agree are valuable are:
* render at root, not at ``/hello/foo``
* use ``renderer='string'`` instead of importing and instantiating the Response object

The code will then look like this:
```python
from wsgiref.simple_server import make_server
from pyramid.config import Configurator

def hello_world(request):
    return 'Hello World'

if __name__ == '__main__':
    config = Configurator()
    config.add_route('hello', '/')
    config.add_view(hello_world, route_name='hello', renderer='string')
    app = config.make_wsgi_app()
    server = make_server('0.0.0.0', 8080, app)
    server.serve_forever()
```

If we want to preserve the "let's show how to get values from the request" display, the code would have to look something like this (note the secondary add_route/add_view):

```python
from wsgiref.simple_server import make_server
from pyramid.config import Configurator

def hello_world(request):
    return 'Hello {}!'.format(request.matchdict.get('name', 'World'))

if __name__ == '__main__':
    config = Configurator()
    config.add_route('hello_world', '/')
    config.add_view(hello_world, route_name='hello_world', renderer='string')
    config.add_route('hello_name', '/{name}')
    config.add_view(hello_world, route_name='hello_name', renderer='string')
    app = config.make_wsgi_app()
    server = make_server('0.0.0.0', 8080, app)
    server.serve_forever()
```

**Comment by stevepiercy** [comment]
I prefer the first code example. Code golf!

**Comment by zupo** [comment]
I'm also leaning more towards the first one.

**Comment by livike** [comment]
Updated with the first code example & deleted the whole `pip install...` part

**Comment by blaflamme** [comment]
I thought that people preferred the @view_config way of registering a view for new comers?

**Comment by mmerickel** [comment]
> I thought that people preferred the @view_config way of registering a view for new comers?

Yes, we made a real effort to update examples to use `@view_config`. We should not go back on that.

**Comment by zupo** [comment]
I'm all for using ``@view_config``! @livike can you please amend the PR (again, I know) to have ``@view_config`` decorator instead of ``add_view`` method?

**Comment by blaflamme** [comment]
and don't forget `config.scan()`

**Comment by livike** [comment]
should be ok now

**Comment by stevepiercy** [comment]
Yup, it works for me. Thank you!

**Comment by stevepiercy** [comment]
Next step is to update instances of Hello World in the Pyramid docs, so I'll make an issue there unless that's already been taken care of.

**Comment by livike** [comment]
Ok thanks, make an issue and I will fix the docs.

**Comment by stevepiercy** [comment]
@livike here it is https://github.com/Pylons/pyramid/issues/2856

**Pull request merged**
