### PR TITLE
Page extending pyramid

### PR DESCRIPTION
**Pull request by stevepiercy**
- [x] Decide which select/data sets should be displayed; update HTML accordingly.
- [x] Provide external JSON dataset, aligned with previous step. [@stevepiercy]
- [x] Add development environments. [@stevepiercy]
- [ ] Import dataset into JSON. [@blaflamme]
- [x] Remove pages `resources-add-ons.html` and `resources-development-environments.html`. [@stevepiercy]
- [x] Update navigation items. [@stevepiercy]
- [x] Improve design.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@blaflamme @ergo I've started a task list. Feel free to edit.

As far as which button sets/filters to use, I'm leaning toward:
* Remove Add-on, because who cares? It's a package. "Add-on" has relevance only to developers of Pyramid add-ons.
* Do not add Tags (e.g., JSON, WSGI, etc.). I pulled those terms from Description for each package, and developers know how to `Command-F`/`CTRL-F` in the browser.

**Comment by blaflamme** [comment]
@stevepiercy here's my take on the grid filtering with a multiselect menu, takes less place and seems more convenient to me. Look at this [branch](https://github.com/Pylons/trypyramid.com/tree/extending-multiselect), don't forget to `$ npm install` and possibly remove `node_modules` if you run into a problem with versions.

Next step is to provide the data to the template to make this a bit more maintainable.

**Comment by stevepiercy** [comment]
@blaflamme YES! I like this much better.

I think that the grid should have only one column, not two, when the screen is phone in portrait orientation. I'll change `col-xs-6` to `col-xs-12`.

The next step is deciding what data to provide. Add-on: yes or no?

How does this example JSON data file structure with two records look to you?

```json
[
    {
        "id": int,
        "name": "str",
        "description": "str",
        "maintainers": "str",
        "support": "str",
        "category": "str",
        "addon": "str",
        "projectUrl": "str",
        "pypiUrl": "str",
        "vcsUrl": "str",
        "docsUrl": "str",
        "demoUrl": "str"
    },
    {
        "id": int,
        "name": "str",
        "description": "str",
        "maintainers": "str",
        "support": "str",
        "category": "str",
        "addon": "str",
        "projectUrl": "str",
        "pypiUrl": "str",
        "vcsUrl": "str",
        "docsUrl": "str",
        "demoUrl": "str"
    }
]
```

**Comment by blaflamme** [comment]
@stevepiercy ok I'll merge my branch with this one to continue here. Sure 1 row will be better for iPhone-like viewport.

For the model I would do tiny adjustments, support is for what?

```
{
  "id": Number,
  "name": String,
  "description": String,
  "maintainers": Array,
  "support": String,
  "category": String,
  "addon": Boolean,
  "projectUrl": String,
  "pypiUrl": String,
  "vcsUrl": String,
  "docsUrl": String,
  "demoUrl": String
}
```

**Comment by stevepiercy** [comment]
@blaflamme OK, merge on!

I'll take on 1-column on vertical phone viewport.

I'll adjust the JSON model accordingly.

Support is whether it is officially supported by Pylons Project, unsupported (Beaker is the lone unsupported package, but was supported at one point by Pylons Project), and Community for non-official.

Thanks for the feedback. I'll resume work after dark here.

**Comment by blaflamme** [comment]
@stevepiercy ok great

**Comment by stevepiercy** [comment]
OK, @blaflamme, my work is done for now. Please look it over, and let me know.

**Comment by stevepiercy** [comment]
@blaflamme how about we merge this PR now and deploy? This PR is blocking other pages I can work on. Then you can work on the JSON dataset import at your leisure. Please let me know. Thank you!

**Comment by blaflamme** [comment]
@stevepiercy done!

**Pull request merged**
