### PR TITLE
Added Rollbar listing and logo

### PR DESCRIPTION
**Pull request by jessewgibbs**

### CODE REVIEW

**Comment by blaflamme** [comment]
@jessewgibbs please add your entry to the community json file here: https://github.com/Pylons/trypyramid.com/blob/master/src/templates/community-powered-by-pyramid.json since the dist files are only produced on releases.

**Comment by blaflamme** [comment]
@jessewgibbs and remove your changes to the dist file

**Comment by stevepiercy** [comment]
Hi @jessewgibbs,

Unfortunately the [diff is completely borked](https://github.com/Pylons/trypyramid.com/pull/219/files), and you need to modify only the source files, so I cannot accept this PR.

The preferred method is to submit an issue using this template:
https://github.com/Pylons/trypyramid.com/issues/162

Or modify the appropriate source file, as @blaflamme mentioned.

Thank you!

**Comment by jessewgibbs** [comment]
@blaflamme @stevepiercy thanks for the feedback.  I'll submit an issue per your suggestion.

**Pull request closed without merging**
