### PR TITLE
Add PyCharm logo and text

### PR DESCRIPTION
**Pull request by stevepiercy**
See #194.
Ping @blaflamme for review and suggestions for improvement

### CODE REVIEW

**Comment by stevepiercy** [comment]
Draft of resources.html:

Draft of resources.html

**Comment by stevepiercy** [comment]
@pauleveritt who inside JetBrains might want to take a look at this proposal for trypyramid.com and offer feedback?

**Comment by pauleveritt** [comment]
Just to be clear, is your point, to review any branding and use-of-logo issues?

—Paul

**Comment by stevepiercy** [comment]
@pauleveritt correct.

**Comment by stevepiercy** [comment]
Here's the updated screenshot. We may not resize the PyCharm logo, according to usage guidelines, and I want to respect that.
google chrome007

**Comment by stevepiercy** [comment]
ping @blaflamme for one more look.

**Comment by stevepiercy** [comment]
"Don't change the dimensions"

If in doubt, please contact marketing@jetbrains.com

I sent email to them for clarification.

@blaflamme otherwise is the placement and arrangement of the components OK?

**Comment by blaflamme** [comment]
@stevepiercy ok great... yes it looks good.

**Comment by stevepiercy** [comment]
This is now done in #198 and #199. Sorry for the sloppy commit history.

**Pull request merged**
