### PR TITLE
Beaker IS being maintained again.

### PR DESCRIPTION
**Pull request by ergo**

### CODE REVIEW

**Comment by stevepiercy** [comment]
@ergo who is maintaining pyramid_beaker? There has not been a release to PyPI for almost 3 years.

I'm more inclined to keep the link to the article and add a note that Beaker is being maintained again as of [date]. I don't know whether any of the issues in that article have been resolved, so *caveat emptor*.

**Comment by ergo** [comment]
@stevepiercy - beaker is maintained again - and had new releases for quite
a while, 3 releases since start of 2015 - latest in 2016 (
https://pypi.python.org/pypi/Beaker?) - looks like its maintained by the
turbogears team.

The "issues" in the article are "non-issues" - sure, dogpile cache is
better in terms of speed vs dogpile.cache,  BUT:

- beaker had security reviews by rehat
- provides encrypted and file or in-memory sessions that people often need
- it also has py 3.x compatibility
- there is support for more exotic backends like tokyo cabinet.

While i use dogpile.cache and pyramid_redis_sessions beaker is still a
valid choice especially now that development was picked up again - its
tried and tested it didn't suddenly stopped working on sites are used by
millions on a daily basis.


2016-06-05 22:59 GMT+02:00 Steve Piercy <notifications@github.com>:

> @ergo <https://github.com/ergo> who is maintaining pyramid_beaker? There
> has not been a release to PyPI for almost 3 years.
>
> I'm more inclined to keep the link to the article and add a note that
> Beaker is being maintained again as of [date]. I don't know whether any of
> the issues in that article have been resolved, so *caveat emptor*.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Pylons/trypyramid.com/pull/143#issuecomment-223837283>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACA_U3k_4rp3WnvO89tC_wQnHQOzynkks5qIzixgaJpZM4IuTlu>
> .
>



-- 
-- 
Marcin Lulek

Webreactor
NIP: PL 725-182-86-80, REGON: 100661081
Pabianice 95-200
20-Stycznia 66/25

**Comment by ergo** [comment]
CC @amol

**Comment by stevepiercy** [comment]
It looks like the biggest issue has been resolved since that article was published, so the article is obsolete:
https://github.com/bbangert/beaker/blob/master/CHANGELOG#L16

I'll merge this, and push it out in the next deployment. Thank you!

However:
* There are differences between Python support in Pyramid and Beaker, so that might be an issue going forward.
* pyramid_beaker is not supported, but if someone qualified were to step up as a maintainer, I'm sure that either @mmerickel or @mcdonc would grant that person access to fulfill that role *nudge* *wink*.

**Pull request merged**
