### PR TITLE
page-powered-by-pyramid: break out each page from PR #30

### PR DESCRIPTION
**Pull request by stevepiercy**
See PR #30, the branch for which may be deleted once this PR is merged.

This page appears as the only page (for now) under the navbar item Community.

See https://github.com/Pylons/trypyramid.com/issues/22 for a list of other items that should go on this page, pending verification.

ping @blaflamme for feedback and design work.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@blaflamme this is ready for your design efforts.

Note that the two SVG logos could not be copied over by webpack because the extension is used for fonts. I am not sure how to deal with that.

**Comment by blaflamme** [comment]
@stevepiercy The data should be split out to a json file like we did for extending pyramid. I think we can also use a grid to present them in a similar way, but we have to set proportions to images and re-save them to ensure consistency.

**Comment by stevepiercy** [comment]
@blaflamme would you please create an example for me to follow for the grid? I'll do any necessary conversions and grunt work. Simple HTML would be a great start.

Note that current logo sizes are inconsistent, some taller than wide, others wider than tall, some square, some absent altogether. An example template will give me a spec to use. 

I have a script that resizes images (logos, products, etc.) to specified dimensions, padded with white pixels. I do this often for product shots that must be square.

**Comment by stevepiercy** [comment]
@blaflamme I have created a PR for each navigation menu and page, and tagged them under the 0.3 milestone: https://github.com/Pylons/trypyramid.com/milestones/v0.3

**Comment by stevepiercy** [comment]
obsolete. closing.

**Pull request closed without merging**
