### PR TITLE
add pyramid-dynamodb-sessions

### LINKED ISSUE #279: Add pyramid-dynamodb-sessions to Extending Pyramid
Name: pyramid-dynamodb-sessions
URL: https://pypi.org/project/pyramid-dynamodb-sessions/
description: DynamoDB-backed sessions
maintainers: luhn
PyPI URL: https://pypi.org/project/pyramid-dynamodb-sessions/
VCS URL: https://github.com/luhn/pyramid-dynamodb-sessions
docs URL: https://pypi.org/project/pyramid-dynamodb-sessions/
demo URL: N/A
support: Community
addon:  Yes
category: sessions
tags: aws, dynamodb, serverless

### PR DESCRIPTION
**Pull request by mmerickel**
fixes #279

### CODE REVIEW

**Comment by mmerickel** [comment]
I didn't see a location to support tags in our current addon model. Maybe I missed it?

**Comment by stevepiercy** [comment]
Correct, there is no tags support. It was a concept that never got implemented. There is category support.

I need to remove the issue templates and provide better instructions for how to contribute to this repo.

**Comment by stevepiercy** [comment]
I've opened a PR #282 to make this process more direct.

**Comment by luhn** [comment]
Docs URL is empty.  I assume this was intentional since it just links to PyPI?

LGTM.

**Comment by stevepiercy** [comment]
Good question about docs. We have never clearly defined what are docs. Is it a README, full narrative, API, tutorials, or all the above? (Hint: all the above.)

I'll add the link, because if someone seeks docs, it just so happens to be the rendered README on PyPI.

**Pull request merged**
