### PR TITLE
Add SoL to Powered by Pyramid

### PR DESCRIPTION
**Pull request by lelit**

### CODE REVIEW

**Comment by lelit** [comment]
I could not verify the commit on my local machine as explained in the README, sorry. I will try that in the following days, if needed.

**Comment by stevepiercy** [comment]
This looks fine. Thank you!

**Comment by lelit** [comment]
Great, but I think I screwed something, as the logo does not appear, it's just a repetition of the site URL...

**Comment by lelit** [comment]
I do not see what's wrong, the logo is there, and the img src seems correct.

**Comment by stevepiercy** [comment]
Oops. Forgot to add it to `src/main.js`. I just did it in another commit. It should shows up now.

I also just updated the readme to include this step.

Note that the logo is not centered. We don't yet have a step to automate resizing of logos onto a 700x200 pixel transparent background, and we rely on contributors to do that step manually. If you can do that, then it will look consistent, else I can take a shot at it.

**Comment by lelit** [comment]
Thank you, I replaced the logo in PR #294.

**Pull request merged**
